import Head from "next/head";
import Dashboard from "@/components/dashboard";
import MultiSocketExample from "@/components/examples/MultiSocketExample";

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>My Dashboard</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head> */}
      {/* <Dashboard /> */}
      <MultiSocketExample />
    </div>
  );
}
